### ISSUE TITLE
[RFC] Feed widgets selected categories state from source filters

### ISSUE THREAD

**Issue by Clebal** [CartoDB/carto-react#196]
### Precedents

Currently, a widget like CategoryWidget have a state called `selectedCategories` that starts empty by default, when the user selects a category, a filter is applied and the selectedCategories state is updated.

### Problem

The problem with this approach is that we're managing widget selected categories in two ways: one inside the widget with the `selectedCategories` state and another one with the source filters. This cause that if the filter that that widget creates is already added (because, for example, we saved a previous state that we want to apply again) in the source, the widget doesn't know it because it doesn't update its internal state with filter value.

### Solution

I'd advocate for removing widget internal `selectedCategories` state and using filter value as replacement to feed the UI and managing the state.

This improvement will be in every widget.

**Comment by borja-munoz** [comment]
I understand your approach involves reading the filter state in the widget initialization and setting the selected categories (CategoryWidget, PieWidget) or bars (HistogramWidget) depending on the current filters applied to the source using the selected `column` property. Also, when you select a category or bar, or clear the selected filters, you will directly updating the filters in the source (as it is done today).

For the categories, I don't see a problem because we have an "IN" filter that should be easy to parse. 

I'm not sure what will be the approach with selected bars in histograms. Imagine we have a histogram widget with ticks = [1, 5, 10] and we have set the following filter in the same column used by the histogram: BETWEEN 3 AND 7. What should we do in this case?

**Comment by borja-munoz** [comment]
Closing this RFC as the approach for using Redux state instead of local state is being implemented in this PR: https://github.com/CartoDB/carto-react/pull/224 by @zbigg

**Comment by VictorVelarde** [comment]
It is indeed. We agree this is a good proposal
